theme: minima
title: Not so painless GitHub journey
author: Bartlomiej Lipinski
email: bartlomiejmlipinski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is done for the pourpouse of training with GitHub.
  It's a warmup before diving into Python.
  This is not the page you are looking for.

# social links
twitter_username: blacklagoonzack # DO NOT include the @ character, or else the build will fail!
github_username:  CStrifeA # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
